language: ruby
rvm:
 - 2.5
 # - jruby

services:
- postgresql

befpre script:
- psql -c 'create database pgapp_test;' -U postgres

script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
